CREATE TABLE tb_employee_categories (
    employee_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (employee_id, category_id),
    CONSTRAINT fk_emp_cat_employee 
        FOREIGN KEY (employee_id) REFERENCES tb_employee(id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_cat_category 
        FOREIGN KEY (category_id) REFERENCES tb_employee_category(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Migrate existing data
INSERT INTO tb_employee_categories (employee_id, category_id)
SELECT id, employee_category_id FROM tb_employee;

-- Drop foreign key and column from tb_employee
-- Note: FK name might vary, but standard flyway/hibernate naming usually follows table_ibfk_X or generic names.
-- However, since I can't be 100% sure of the constraint name generated by the previous manual SQL or Hibernate if it was auto-generated,
-- I'll try to drop the Foreign Key by the column name if possible, or assume a standard name.
-- Looking at V1__Initial_Schema.sql:
-- FOREIGN KEY (employee_category_id) REFERENCES tb_employee_category (id)
-- MySQL usually names this tb_employee_ibfk_1 given it's the first FK in the table definition order in V1 if created manually without constraint name.
-- To be safe, let's verify constraint names? No, I can't interactively check in a migration easily without dynamic SQL which is complex in Flyway.
-- Given V1 has: FOREIGN KEY (employee_category_id) REFERENCES tb_employee_category (id)
-- And it is the first FK.
-- I will assume the index name might be employee_category_id or fk_something.
-- Let's try to drop the FK by explicitly naming the one likely created or using a procedure to find it? 
-- A simpler approach for this environment:
-- The V1 file didn't name the constraint. MySQL auto-generates it.
-- Usually `tb_employee_ibfk_1`.

ALTER TABLE tb_employee DROP FOREIGN KEY tb_employee_ibfk_1;
ALTER TABLE tb_employee DROP COLUMN employee_category_id;
